[package]
name = "graph6-rs"
version = "0.1.0"
edition = "2021"
keywords = [ "parser", "graphs", "graph6", "nauty" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
